const CART_ADD_PIZZA = 'CART_ADD_PIZZA';
const CART_UPDATE_PIZZA_QUANTITY = 'CART_UPDATE_PIZZA_QUANTITY';
const CART_REMOVE_PIZZA = 'CART_REMOVE_PIZZA';

const CART_ADD_EXTRA = 'CART_ADD_EXTRA';
const CART_UPDATE_EXTRA_QUANTITY = 'CART_UPDATE_EXTRA_QUANTITY';
const CART_REMOVE_EXTRA = 'CART_REMOVE_EXTRA';

const CART_CLEAR = 'CART_CLEAR';
const CART_CLEAR_ALL = 'CART_CLEAR_ALL';

export default {
    CART_ADD_PIZZA,
    CART_UPDATE_PIZZA_QUANTITY,
    CART_REMOVE_PIZZA,
    CART_ADD_EXTRA,
    CART_UPDATE_EXTRA_QUANTITY,
    CART_REMOVE_EXTRA,
    CART_CLEAR,
    CART_CLEAR_ALL
};